//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsMania.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Contact { get; set; }
        public string Message1 { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public string RecieverID { get; set; }
        public bool Seen { get; set; }
        public Nullable<System.DateTime> SeenTime { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
